version = 0.1
[default.deploy.parameters]
stack_name = "quarkus-native-stack"
resolve_s3 = true
s3_prefix = "quarkus-native-stack"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
