AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Quarkus - quarkus-amazon-lambda-common-deployment
Globals:
  Api:
    BinaryMediaTypes:
      - "*/*"
  Function:
    Timeout: 30  # Timeout in seconds
    Environment:
      Variables:
        SQS_QUEUE_OUTPUT_URL: !Ref OutputQueue
Resources:
  # Input Queue
  InputQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: InputQueue
  
  # Input Queue
  InputQueue2:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: InputQueue2

  # Output Queue
  OutputQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: OutputQueue

  # Dead Letter Queue
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: LambdaDLQ

  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess

  QuarkusLambdaNative:
    Type: AWS::Serverless::Function
    Properties:
      Handler: not.used.in.provided.runtime
      Runtime: provided.al2023
      CodeUri: target/function.zip
      MemorySize: 128
      # Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt InputQueue.Arn
            BatchSize: 1
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt DeadLetterQueue.Arn
      Environment:
        Variables:
          DISABLE_SIGNAL_HANDLERS: true
          
  QuarkusLambdaImage:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: 807149668622.dkr.ecr.ap-southeast-1.amazonaws.com/my/test/quarkus-lambda:v1
      MemorySize: 128
      Timeout: 15
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt InputQueue2.Arn
            BatchSize: 1
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt DeadLetterQueue.Arn
      Environment:
        Variables:
          DISABLE_SIGNAL_HANDLERS: true
          
Outputs:
  LambdaFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt QuarkusLambdaNative.Arn

  InputQueueURL:
    Description: "URL of Input Queue"
    Value: !Ref InputQueue

  InputQueue2URL:
    Description: "URL of Input Queue"
    Value: !Ref InputQueue2


  OutputQueueURL:
    Description: "URL of Output Queue"
    Value: !Ref OutputQueue
