FROM public.ecr.aws/lambda/provided:al2023

ENV BUILD_VERSION=1.0-SNAPSHOT

ADD target/quarkus-lambda-${BUILD_VERSION}-runner /var/runtime/bootstrap
RUN chmod ugo+x /var/runtime/bootstrap

CMD ["io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest"]